---
- name: config_interfaces | Configuring Loopback Interfaces
  template:
    src: "etc/network/interfaces.d/int.cfg.j2"
    dest: "/etc/network/interfaces.d/{{ item.int }}.cfg"
  register: "loopback_interfaces_configured"
  with_items: '{{ quagga_interfaces_lo }}'
  when: >
        quagga_interfaces_lo is defined and
        item.configure

- name: config_interfaces | Restarting Loopback Interfaces
  shell: bash -c "ifdown {{ item.int }} && ifup {{ item.int }}"
  with_items: '{{ quagga_interfaces_lo }}'
  when: >
        quagga_interfaces_lo is defined and
        item.configure and
        loopback_interfaces_configured.changed

- name: config_interfaces | Shutting Down Loopback Interfaces (Un-Configured)
  shell: bash -c "ifdown {{ item.int }}"
  register: "loopback_interfaces_shutdown"
  with_items: '{{ quagga_interfaces_lo }}'
  when: not item.configure

- name: config_interfaces | Removing Loopback Interfaces (Un-Configured)
  file:
    path: "/etc/network/interfaces.d/{{ item.int }}.cfg"
    state: "absent"
  with_items: '{{ quagga_interfaces_lo }}'
  when: loopback_interfaces_shutdown.changed

- name: config_interfaces | Configuring Interfaces
  template:
    src: "etc/network/interfaces.d/int.cfg.j2"
    dest: "/etc/network/interfaces.d/{{ item.int }}.cfg"
  register: "interfaces_configured"
  with_items: '{{ quagga_interfaces }}'
  when: >
        quagga_interfaces is defined and
        item.configure

- name: config_interfaces | Restarting Interfaces
  shell: bash -c "ifdown {{ item.int }} && ifup {{ item.int }}"
  with_items: '{{ quagga_interfaces }}'
  when: >
        quagga_interfaces is defined and
        item.configure and
        interfaces_configured.changed

- name: config_interfaces | Shutting Down Interfaces (Un-Configured)
  shell: bash -c "ifdown {{ item.int }}"
  register: "interfaces_shutdown"
  with_items: '{{ quagga_interfaces }}'
  when: not item.configure

- name: config_interfaces | Removing Interfaces (Un-Configured)
  file:
    path: "/etc/network/interfaces.d/{{ item.int }}.cfg"
    state: "absent"
  with_items: '{{ quagga_interfaces }}'
  when: interfaces_shutdown.changed
